### ISSUE TITLE
Current master branch doesn't appear to allow running either todo or expression-problem

### ISSUE THREAD

**Issue by eswenson1** [DevInsideYou/tagless-final#1]
For example:

> $ sbt
> [info] welcome to sbt 1.3.13 (Oracle Corporation Java 1.8.0_181)
> [info] loading global plugins from /Users/eswenson/.sbt/1.0/plugins
> [info] loading settings for project todo-build-build from plugins.sbt ...
> [info] loading project definition from /Users/eswenson/Personal/src/scala/tagless-final/todo/project/project
> [info] loading settings for project todo-build from plugins.sbt ...
> [info] loading project definition from /Users/eswenson/Personal/src/scala/tagless-final/todo/project
> [info] loading settings for project todo from sbt.sbt,aliases.sbt,build.sbt ...
> [info] set current project to todo (in build file:/Users/eswenson/Personal/src/scala/tagless-final/todo/)
> [info] ───────────────────────────
> [info]   List of defined aliases
> [info] ────────┬──────────────────
> [info] cd      │ project
> [info] root    │ cd todo
> [info] c       │ compile
> [info] ca      │ compile all
> [info] t       │ test
> [info] r       │ run
> [info] up2date │ dependencyUpdates
> [info] ────────┴──────────────────
> git:master:7cb962a:sbt:todo> r
> [error] java.lang.RuntimeException: No main class detected.
> [error] 	at scala.sys.package$.error(package.scala:30)
> [error] stack trace is suppressed; run last Compile / bgRun for the full output
> [error] (Compile / bgRun) No main class detected.
> [error] Total time: 0 s, completed Jul 3, 2020 9:11:27 AM
> git:master:7cb962a:sbt:todo>

**Comment by eswenson1** [comment]
I tried running from various commits and each resulted in the same error -- no main class detected.  Since I'm watching video 2 now, I tried 485bfddac99cb8ccb653c411ddda7323265b37ec, for example and got the same error.  This commit has this commit log:
```commit 485bfddac99cb8ccb653c411ddda7323265b37ec
Author: Vladyslav Pekker <agilesteel<redacted>>
Date:   Sun May 3 13:19:49 2020 -0300

    Video 2
```

**Comment by agilesteel** [comment]
Hi, they are both multibuild projects. Type `projects` to list all the sub projects and then `project main` or `cd main`. From there you can `run` or `r`. Cheers :)

**Comment by eswenson1** [comment]
Ah, thanks. I missed that.  I thought the repo was multi-project, and not each of todo and expression-problem, themselves were multi-project.  Sorry.
